### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by peanutbutterlou** [arcanedreams/ArcManagedFBX#2]
Would you be willing to assign an open source license to this project?

**Comment by LoveDuckie** [comment]
Possibly. Why, how are you intending on using the code?

**Comment by peanutbutterlou** [comment]
I want to use it for an internal tool for the company I work for. It's a WPF app that will assist artists by performing validation against the FBX files they export from Maya or 3ds Max. I'd also would be extending it to wrap a handful more of the classes provided by the FBX SDK and to target the latest version of the FBX SDK. Oh, and to bulk convert FBX files from silly ASCII format to binary.

**Comment by LoveDuckie** [comment]
I'll try to find some time to look into it this weekend, but not sure if it's going to be done before you go to work on Monday. I'm fine with you using it as you like, though.

**Comment by LoveDuckie** [comment]
Apologies for leaving this so late. As I've mentioned before, feel free to use it as you see fit. I will probably put it under the MIT license.

**Comment by ZNixian** [comment]
Hello,

Is there any chance you could officially put this under an open-source licence?

I'm working on some open-source game modding tools where something like this would be very handy.

**Comment by LoveDuckie** [comment]
Hi @ZNixian 

Do you have any suggestions as to which open-source license would be appropriate? Happy to look into it.

I will be honest in saying that I am a bit apprehensive in licensing this source code, as it's based on a proprietary technology that belongs to Autodesk.

I'd also be curious to hear more about what you are doing with game tooling. Send me an email at [github@arcanedreams.com](mailto:github@arcanedreams.com). Perhaps we can help each other.

**Comment by ZNixian** [comment]
I would personally suggest the MIT licence - it's very short and is compatible with basically everything.

Both the Apache 2 licence and the GNU GPL have trouble integrating with proprietary software, either due to redistribution requirements (GPL 2/3) and patent requirements (Apache 2 / GPL 3).

You can use Apache 2 or the GPL if you make an exception to them, however it's probably quite a bit easier just to use the MIT licence, if you want a everyone-can-use-it type of thing.

I've done something somewhat similar before - one of my open-source projects ([OpenComposite](https://gitlab.com/znixian/OpenOVR)) uses the proprietary Oculus SDK.

My solution was to licence the code I wrote under a compatible open-source licence (GPL3 with an exception permitting the use of the Oculus SDK), however I don't distribute the actual Oculus SDK - people have to download that themselves from the Oculus website, then extract it into a clearly-marked folder.

(note that I chose the GPL3 since OpenComposite is a stand-alone program, not a library)

That would be my general advice for projects like this - licence just your code with MIT (and be clear that when compiled the user must observe Autodesk's licence), and have other people download the FBX SDK and install it into `Libs/FBX`, when people can then agree to it's terms.

That way you can be clear that the user is still having to use the library under Autodesk's licence, and it's only the code you own that is under the MIT licence.

**Comment by LoveDuckie** [comment]
Thanks for your detailed advice, it's greatly appreciated.

I've taken a look at the MIT license and I think it aligns well with my intent. I've created a new _LICENSE_ file specifying the [MIT license.](https://choosealicense.com/licenses/mit/#)

Closing this. Will reply to your e-mail.

**Comment by ZNixian** [comment]
Awesome, thank you very much.
