### ISSUE TITLE
VS 2013 build..

### ISSUE THREAD

**Issue by mikeoverbay** [arcanedreams/ArcManagedFBX#3]
Hey there...
I forked and cloned the repository to my local system.
I managed to get it to build in debug mode but in release, I'm getting around 700 unresolved externals during linking.
I'm wondering if you have any clue what could be causing this.
I have changed the paths for the debug and release and made sure I'm in X86 mode.

Nice work!.. I can see this project was a huge undertaking.
I have been using an old wrapper from 1012 and it doesn't have some of the methods I need.. like grabbing the tangents and bi-normals from the mesh.
Thanks for putting this work out there so others may learn from it and hopefully, create some cool stuff.

**Comment by mikeoverbay** [comment]
I should of mentioned this..
I have Visual Studio 2013 Pro. I'm running good ol' Win 7 64 Pro.
Thanks again...

**Comment by LoveDuckie** [comment]
Hey @mikeoverbay!

Thanks for the kind words, it's nice to know that you've been able to find some usage for it even if it's not compiling right now! When I worked on this project, it was a good exercise in understanding how the garbage collection routines for CLR worked and how best to write a .NET/CLR wrapper that leveraged C++/CLI. My goal with this project was to create a complete FBX wrapper in .NET so that it could be used with the MonoGame Content Pipeline for importing FBX assets on a Windows machine.

To respond to your problem: you might need to install the 2015 FBX SDK before compiling, as it's likely trying to find the static libraries to link against. I didn't commit these part of the project as they are copyrighted and it needlessly inflates the size of the repository with "non-diffable" content. From my understanding, Git is not very good at handling binaries.

Sorry for responding to your comment so late. I don't pay much attention to GitHub notifications. More than happy to help with any other queries!

**Comment by LoveDuckie** [comment]
[FYI: You can find the FBX 2015 SDK right here.](http://usa.autodesk.com/adsk/servlet/pc/item?siteID=123112&id=10775847)

**Comment by mikeoverbay** [comment]
No problem with being late... At least you answered.. :) I usually never hear back.
I have the 2015 sdk installed..
I guess I need to dig in to this deeper. It has to be a path issue but I wasn't able to sort it out.. 
Thanks again !

**Comment by LoveDuckie** [comment]
It might well be. Verify the build configurations to make sure there are no errors.

I will likely support this again in the future as I was intending on using it with other projects. My full-time job takes up most of my time, unfortunately. Thanks for getting in touch.

**Comment by mikeoverbay** [comment]
Hey.. I understand that there are more important things in life.. like Eating :)
If you ever do decide to work on this again, please drop me a message.. 
Thanks again for all the effort on this!!!

**Comment by LoveDuckie** [comment]
I will definitely look at working on this again in the future. I have other priorities right now but I want to come back to my MonoGame projects, and this will definitely be one of the things that I will take a look at. :)

In the meantime, feel free to e-mail me at [luc.shelton@arcanedreams.com](mailto:luc.shelton@arcanedreams.com) if you have any questions.
